---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: groundhog2k-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://groundhog2k.github.io/helm-charts/
  timeout: 2m
