---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aquasecurity-charts.yaml
  - bitnami-charts.yaml
  - bjw-s.yaml
  - csi-driver-nfs-charts.yaml
  - datahub-charts.yaml
  - descheduler-charts.yaml
  - external-dns-charts.yaml
  - grafana-charts.yaml
  - groundhog2k-charts.yaml
  - influxdata-charts.yaml
  - ingress-nginx-charts.yaml
  - jetstack-charts.yaml
  - k8s-at-home-charts.yaml
  - metallb-charts.yaml
  - metrics-server-charts.yaml
  - mojo2600-charts.yaml
  - neo4j-charts.yaml
  - strimzi-charts.yaml
  - traefik-charts.yaml
  - ytdl-material-charts.yaml
  - z2jh-charts.yaml
