---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: mojo2600-charts
  namespace: flux-system
spec:
  interval: 30m
  url: https://mojo2600.github.io/pihole-kubernetes/
  timeout: 2m
