---
name: "Meta Labeler"

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  labeler:
    name: Labeler
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@0967ca812e7fdc8f5f71402a1b486d5bd061fe20 # v4
        with:
          configuration-path: .github/labeler.yaml
    # runs-on: ubuntu-latest
    # steps:
    #   - name: Generate Token
    #     uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
    #     id: generate-token
    #     with:
    #       app_id: "${{ secrets.BOT_APP_ID }}"
    #       private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

    #   - name: Labeler
    #     uses: actions/labeler@ba790c862c380240c6d5e7427be5ace9a05c754b # v4.0.3
    #     with:
    #       configuration-path: .github/labeler.yaml
    #       repo-token: "${{ steps.generate-token.outputs.token }}"
